module.exports = {
  UserService: require("./user-service"),
  CountryService: require("./country-service"),
  StateService: require("./state-service"),
  CityService: require("./city-service"),
  JobSeekerService: require("./jobseeker-service"),
  JobSeekerEducationService: require("./jobseekereducation-service"),
  JobSeekerExperienceService: require("./jobseekerexperience-service"),
  JobSeekerResumeService: require("./jobseekerresume-service"),
  VideoService: require("./video-service"),
  SkillService: require("./skill-service"),
  EmployerSerevice: require("./employer-service"),
  JobService: require("./job-service"),
  OTPService: require("./otp-service"),
};
