module.exports = {
  UserRepository: require("./user-repository"),
  TypeRepository: require("./type-repository"),
  CountryRepository: require("./country-repository"),
  StateRepository: require("./state-repository"),
  CityRepository: require("./city-repository"),
  JobSeekerRepository: require("./jobseeker-repository"),
  JobSeekerEducationRepository: require("./jobseekereducation-repository"),
  JobSeekerExperienceRepository: require("./jobseekerexperience-repository"),
  JobSeekerResumeRepository: require("./jobseekerresume-repository"),
  VideoRepository: require("./video-repository"),
  SkillRepository: require("./skill-repository"),
  EmployerRepository: require("./employer-repository"),
  JobRepository: require("./job-repository"),
  OTPRepository: require("./otp-repository"),
};
